# Generated by Django 4.0.3 on 2022-03-23 12:17

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('MS', 'Mississippi'), ('MI', 'Michigan'), ('AL', 'Alabama'), ('OH', 'Ohio'), ('AZ', 'Arizona'), ('CT', 'Connecticut'), ('VT', 'Vermont'), ('MD', 'Maryland'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('IN', 'Indiana'), ('WY', 'Wyoming'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('RI', 'Rhode Island'), ('MT', 'Montana'), ('TX', 'Texas'), ('IL', 'Illinois'), ('NY', 'New York'), ('VA', 'Virginia'), ('ND', 'North Dakota'), ('KY', 'Kentucky'), ('GA', 'Georgia'), ('IA', 'Iowa'), ('SC', 'South Carolina'), ('FL', 'Florida'), ('MA', 'Massachusetts'), ('OR', 'Oregon'), ('MO', 'Missouri'), ('CA', 'California'), ('DC', 'District Of Columbia'), ('WI', 'Wisconsin'), ('LA', 'Louisiana'), ('MN', 'Minnesota'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('AK', 'Alaska'), ('KS', 'Kansas'), ('NJ', 'New Jersey'), ('CO', 'Colorado'), ('ID', 'Idaho'), ('PA', 'Pennsylvania'), ('UT', 'Utah'), ('DE', 'Delaware'), ('HI', 'Hawaii'), ('NC', 'North Carolina'), ('ME', 'Maine'), ('NM', 'New Mexico'), ('AR', 'Arkansas'), ('OK', 'Oklahoma')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car_photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Audio Interface', 'Audio Interface'), ('Wind Deflector', 'Wind Deflector'), ('Airbags', 'Airbags'), ('Power Steering', 'Power Steering'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Cruise Control', 'Cruise Control'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Air Conditioning', 'Air Conditioning')], max_length=195)),
                ('body_style', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('doors', models.CharField(choices=[('4', '4'), ('2', '2'), ('3', '3'), ('5', '5'), ('6', '6')], max_length=10)),
                ('passengers', models.IntegerField()),
                ('vin_no', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 23, 13, 17, 17, 266456))),
            ],
        ),
    ]
