# Generated by Django 4.0.3 on 2022-04-04 16:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('4', '4'), ('6', '6'), ('2', '2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Power Steering', 'Power Steering'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Airbags', 'Airbags'), ('Reversing Camera', 'Reversing Camera'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Auto Start/Stop', 'Auto Start/Stop')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('MO', 'Missouri'), ('ID', 'Idaho'), ('ND', 'North Dakota'), ('NJ', 'New Jersey'), ('MN', 'Minnesota'), ('VT', 'Vermont'), ('OK', 'Oklahoma'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('OH', 'Ohio'), ('WV', 'West Virginia'), ('AK', 'Alaska'), ('WY', 'Wyoming'), ('NE', 'Nebraska'), ('CA', 'California'), ('DC', 'District Of Columbia'), ('WA', 'Washington'), ('AL', 'Alabama'), ('MS', 'Mississippi'), ('IN', 'Indiana'), ('OR', 'Oregon'), ('TX', 'Texas'), ('GA', 'Georgia'), ('WI', 'Wisconsin'), ('SC', 'South Carolina'), ('PA', 'Pennsylvania'), ('NH', 'New Hampshire'), ('RI', 'Rhode Island'), ('LA', 'Louisiana'), ('NC', 'North Carolina'), ('FL', 'Florida'), ('AR', 'Arkansas'), ('NV', 'Nevada'), ('VA', 'Virginia'), ('SD', 'South Dakota'), ('ME', 'Maine'), ('MT', 'Montana'), ('NY', 'New York'), ('KS', 'Kansas'), ('CT', 'Connecticut'), ('MA', 'Massachusetts'), ('KY', 'Kentucky'), ('AZ', 'Arizona'), ('MI', 'Michigan'), ('DE', 'Delaware'), ('IL', 'Illinois'), ('MD', 'Maryland'), ('TN', 'Tennessee'), ('CO', 'Colorado'), ('UT', 'Utah'), ('NM', 'New Mexico')], max_length=100),
        ),
    ]
