# Generated by Django 4.0.3 on 2022-04-04 16:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_created_date_alter_car_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('6', '6'), ('5', '5'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Direct Fuel Injection', 'Direct Fuel Injection'), ('Cruise Control', 'Cruise Control'), ('Airbags', 'Airbags'), ('Audio Interface', 'Audio Interface'), ('Wind Deflector', 'Wind Deflector'), ('ParkAssist', 'ParkAssist'), ('Reversing Camera', 'Reversing Camera'), ('Air Conditioning', 'Air Conditioning'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Power Steering', 'Power Steering'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AR', 'Arkansas'), ('ND', 'North Dakota'), ('AZ', 'Arizona'), ('OR', 'Oregon'), ('TN', 'Tennessee'), ('NH', 'New Hampshire'), ('KS', 'Kansas'), ('VA', 'Virginia'), ('IL', 'Illinois'), ('MT', 'Montana'), ('PA', 'Pennsylvania'), ('ME', 'Maine'), ('UT', 'Utah'), ('WI', 'Wisconsin'), ('NC', 'North Carolina'), ('DE', 'Delaware'), ('AK', 'Alaska'), ('ID', 'Idaho'), ('DC', 'District Of Columbia'), ('GA', 'Georgia'), ('WA', 'Washington'), ('MA', 'Massachusetts'), ('MN', 'Minnesota'), ('CT', 'Connecticut'), ('KY', 'Kentucky'), ('MI', 'Michigan'), ('CO', 'Colorado'), ('WV', 'West Virginia'), ('WY', 'Wyoming'), ('IN', 'Indiana'), ('HI', 'Hawaii'), ('AL', 'Alabama'), ('FL', 'Florida'), ('IA', 'Iowa'), ('MD', 'Maryland'), ('MS', 'Mississippi'), ('TX', 'Texas'), ('NM', 'New Mexico'), ('OH', 'Ohio'), ('NE', 'Nebraska'), ('OK', 'Oklahoma'), ('LA', 'Louisiana'), ('NJ', 'New Jersey'), ('VT', 'Vermont'), ('NY', 'New York'), ('SC', 'South Carolina'), ('RI', 'Rhode Island'), ('CA', 'California'), ('MO', 'Missouri'), ('SD', 'South Dakota'), ('NV', 'Nevada')], max_length=100),
        ),
    ]
