# Generated by Django 4.0.3 on 2022-04-04 16:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_doors_alter_car_features_alter_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('3', '3'), ('6', '6'), ('5', '5'), ('2', '2'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wind Deflector', 'Wind Deflector'), ('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'), ('Cruise Control', 'Cruise Control'), ('Power Steering', 'Power Steering'), ('Seat Heating', 'Seat Heating'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Airbags', 'Airbags'), ('Reversing Camera', 'Reversing Camera'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('VT', 'Vermont'), ('AR', 'Arkansas'), ('IN', 'Indiana'), ('TN', 'Tennessee'), ('AL', 'Alabama'), ('ID', 'Idaho'), ('VA', 'Virginia'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('GA', 'Georgia'), ('NJ', 'New Jersey'), ('PA', 'Pennsylvania'), ('DC', 'District Of Columbia'), ('OK', 'Oklahoma'), ('KS', 'Kansas'), ('OH', 'Ohio'), ('IA', 'Iowa'), ('MD', 'Maryland'), ('RI', 'Rhode Island'), ('WA', 'Washington'), ('UT', 'Utah'), ('CO', 'Colorado'), ('ME', 'Maine'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('KY', 'Kentucky'), ('MS', 'Mississippi'), ('SC', 'South Carolina'), ('IL', 'Illinois'), ('SD', 'South Dakota'), ('HI', 'Hawaii'), ('AK', 'Alaska'), ('CA', 'California'), ('CT', 'Connecticut'), ('AZ', 'Arizona'), ('MA', 'Massachusetts'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('TX', 'Texas'), ('NY', 'New York'), ('OR', 'Oregon'), ('LA', 'Louisiana'), ('MT', 'Montana'), ('NM', 'New Mexico'), ('FL', 'Florida'), ('MI', 'Michigan'), ('WY', 'Wyoming'), ('ND', 'North Dakota'), ('DE', 'Delaware'), ('NV', 'Nevada'), ('NC', 'North Carolina')], max_length=100),
        ),
    ]
