# Generated by Django 4.0.3 on 2022-04-04 16:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_doors_alter_car_features_alter_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('2', '2'), ('5', '5'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Reversing Camera', 'Reversing Camera'), ('ParkAssist', 'ParkAssist'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Alarm System', 'Alarm System'), ('Air Conditioning', 'Air Conditioning'), ('Cruise Control', 'Cruise Control'), ('Wind Deflector', 'Wind Deflector'), ('Power Steering', 'Power Steering'), ('Seat Heating', 'Seat Heating'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Auto Start/Stop', 'Auto Start/Stop')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('OR', 'Oregon'), ('ME', 'Maine'), ('OH', 'Ohio'), ('DC', 'District Of Columbia'), ('WI', 'Wisconsin'), ('AL', 'Alabama'), ('DE', 'Delaware'), ('VT', 'Vermont'), ('NH', 'New Hampshire'), ('HI', 'Hawaii'), ('NV', 'Nevada'), ('TX', 'Texas'), ('RI', 'Rhode Island'), ('WA', 'Washington'), ('TN', 'Tennessee'), ('LA', 'Louisiana'), ('ND', 'North Dakota'), ('MD', 'Maryland'), ('CO', 'Colorado'), ('OK', 'Oklahoma'), ('IA', 'Iowa'), ('NC', 'North Carolina'), ('VA', 'Virginia'), ('NJ', 'New Jersey'), ('SD', 'South Dakota'), ('AR', 'Arkansas'), ('PA', 'Pennsylvania'), ('UT', 'Utah'), ('MN', 'Minnesota'), ('CA', 'California'), ('FL', 'Florida'), ('KY', 'Kentucky'), ('AK', 'Alaska'), ('CT', 'Connecticut'), ('SC', 'South Carolina'), ('MA', 'Massachusetts'), ('ID', 'Idaho'), ('NY', 'New York'), ('WV', 'West Virginia'), ('IL', 'Illinois'), ('WY', 'Wyoming'), ('GA', 'Georgia'), ('AZ', 'Arizona'), ('MO', 'Missouri'), ('IN', 'Indiana'), ('MT', 'Montana'), ('NM', 'New Mexico'), ('KS', 'Kansas'), ('MI', 'Michigan'), ('NE', 'Nebraska'), ('MS', 'Mississippi')], max_length=100),
        ),
    ]
