# Generated by Django 4.0.3 on 2022-04-04 18:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_doors_alter_car_features_alter_car_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='milage',
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('5', '5'), ('4', '4'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Auto Start/Stop', 'Auto Start/Stop'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Cruise Control', 'Cruise Control'), ('Wind Deflector', 'Wind Deflector'), ('Power Steering', 'Power Steering'), ('Airbags', 'Airbags'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Reversing Camera', 'Reversing Camera')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('VA', 'Virginia'), ('NM', 'New Mexico'), ('NH', 'New Hampshire'), ('ME', 'Maine'), ('FL', 'Florida'), ('NJ', 'New Jersey'), ('GA', 'Georgia'), ('AK', 'Alaska'), ('MT', 'Montana'), ('MO', 'Missouri'), ('NY', 'New York'), ('MA', 'Massachusetts'), ('OH', 'Ohio'), ('KY', 'Kentucky'), ('OR', 'Oregon'), ('DC', 'District Of Columbia'), ('HI', 'Hawaii'), ('TX', 'Texas'), ('CO', 'Colorado'), ('OK', 'Oklahoma'), ('IA', 'Iowa'), ('NC', 'North Carolina'), ('SC', 'South Carolina'), ('UT', 'Utah'), ('WV', 'West Virginia'), ('LA', 'Louisiana'), ('MD', 'Maryland'), ('AR', 'Arkansas'), ('TN', 'Tennessee'), ('NV', 'Nevada'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('IL', 'Illinois'), ('AZ', 'Arizona'), ('CA', 'California'), ('CT', 'Connecticut'), ('ND', 'North Dakota'), ('PA', 'Pennsylvania'), ('NE', 'Nebraska'), ('VT', 'Vermont'), ('WA', 'Washington'), ('MN', 'Minnesota'), ('DE', 'Delaware'), ('SD', 'South Dakota'), ('AL', 'Alabama'), ('WI', 'Wisconsin'), ('MI', 'Michigan'), ('MS', 'Mississippi'), ('WY', 'Wyoming'), ('RI', 'Rhode Island'), ('ID', 'Idaho')], max_length=100),
        ),
    ]
