# Generated by Django 4.0.3 on 2022-04-04 20:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_milage_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('4', '4'), ('3', '3'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Servo', 'Servo'), ('Tempomat', 'Tempomat'), ('Bluetooth', 'Bluetooth'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Audio interfejs', 'Audio interfejs'), ('Klima', 'Klima'), ('Alarm', 'Alarm'), ('Grejanje sedista', 'Grejanje sedista'), ('Airbags', 'Airbags'), ('Pomoć prilikom parkiranja', 'Pomoć prilikom parkiranja'), ('Rikverc kamera', 'Rikverc kamera'), ('Direktno ubrizgavanje goriva', 'Direktno ubrizgavanje goriva')], max_length=163),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('SO', 'Sombor')], max_length=100),
        ),
    ]
