# Generated by Django 4.0.3 on 2022-04-05 10:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_doors_alter_car_features_alter_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Klima', 'Klima'), ('Pomoć prilikom parkiranja', 'Pomoć prilikom parkiranja'), ('Direktno ubrizgavanje goriva', 'Direktno ubrizgavanje goriva'), ('Servo', 'Servo'), ('Audio interfejs', 'Audio interfejs'), ('Alarm', 'Alarm'), ('Rikverc kamera', 'Rikverc kamera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Grejanje sedista', 'Grejanje sedista'), ('Airbags', 'Airbags'), ('Bluetooth', 'Bluetooth'), ('Tempomat', 'Tempomat')], max_length=163),
        ),
    ]
