# Generated by Django 4.0.3 on 2022-04-05 10:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_doors_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('3', '3'), ('6', '6'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Servo', 'Servo'), ('Audio interfejs', 'Audio interfejs'), ('Airbags', 'Airbags'), ('Direktno ubrizgavanje goriva', 'Direktno ubrizgavanje goriva'), ('Rikverc kamera', 'Rikverc kamera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Tempomat', 'Tempomat'), ('Alarm', 'Alarm'), ('Bluetooth', 'Bluetooth'), ('Klima', 'Klima'), ('Grejanje sedista', 'Grejanje sedista'), ('Pomoć prilikom parkiranja', 'Pomoć prilikom parkiranja')], max_length=163),
        ),
    ]
