# Generated by Django 4.0.3 on 2022-04-05 14:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_doors_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('2', '2'), ('6', '6'), ('5', '5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Grejanje sedista', 'Grejanje sedista'), ('Pomoć prilikom parkiranja', 'Pomoć prilikom parkiranja'), ('Rikverc kamera', 'Rikverc kamera'), ('Audio interfejs', 'Audio interfejs'), ('Klima', 'Klima'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Airbags', 'Airbags'), ('Direktno ubrizgavanje goriva', 'Direktno ubrizgavanje goriva'), ('Servo', 'Servo'), ('Bluetooth', 'Bluetooth'), ('Alarm', 'Alarm'), ('Tempomat', 'Tempomat')], max_length=163),
        ),
    ]
