# Generated by Django 4.0.3 on 2022-04-05 14:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_car_doors_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('6', '6'), ('2', '2'), ('3', '3'), ('5', '5'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bluetooth', 'Bluetooth'), ('Pomoć prilikom parkiranja', 'Pomoć prilikom parkiranja'), ('Audio interfejs', 'Audio interfejs'), ('Direktno ubrizgavanje goriva', 'Direktno ubrizgavanje goriva'), ('Klima', 'Klima'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Rikverc kamera', 'Rikverc kamera'), ('Alarm', 'Alarm'), ('Grejanje sedista', 'Grejanje sedista'), ('Airbags', 'Airbags'), ('Servo', 'Servo'), ('Tempomat', 'Tempomat')], max_length=163),
        ),
    ]
